ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: no-commit-to-branch
  - id: debug-statements
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.5
  hooks:
  - id: ruff-format
  - id: ruff
    args: [--fix]

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    args: [--ignore-words-list, 'mutch, ore']

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.8
  hooks:
  - id: bandit
    # B101 is assert statements
    args: [--recursive, --skip, B101, .]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
