language: python
dist: xenial
os: linux

env:
  global:
    - TWINE_USERNAME=1313e
    - secure: "i8vL+y1qXy37yXkaDx7gdJIgCRo+5ltmJIj3UZ76WVv2H/JG0fMH5aCYQO3ZS0LfIapXK3whA3wL3kN/D9uUjNOKj8lVVPYbs9ft/V0K3UwCYrTz+mGlXKp8lbWrOc3UI+79ABdKg6CgiVrKLaLan/+Oim8jUXa05XrV3qVwuxbe4HWAQIHOplMKq5K75vuviZsBiVe37AOx9Z3xJdK52U/AetUuphQgKxY4j7kE0bH+MItJqJWsZaJNCSAuk7FkeNNOl0wfX3tEsZ9Q0YtN4DAke95LFVLtmbbjmTshWmP2DnkeA1BWsqCOqTVEfLAfOUo+13s8QPFUQ/dAE11yAcZk95JN1ohNawMc/F+T3qKRFWOWrn/a6ZdQ/5fTtETDpMrp0198AjyhS0L+wBOVnIXq+bclgmpAQg6Jajk8HacnihjC/v5YIGgRc1LS5tiDMqm+NjLhnjWv/iC1YRQcE0gC1W+5vJ3gNyEDJmjDzdkkdlMqvGK8X8Ig+QWP9Wphl+4i6d9M41ohsH+ZgaEigUkLKNnwbHXQKteYZ1gFzKhFvoikwqpY8F7Oi6adyuMPzpBXRwBwPRNk/f3dTIOYlWW/S4Ziu7vTxDaLk/mF/NaBujY7tv+wHOHYTW+5JR3SpTRtgcXRiym/do5dKwE5StUybXbpzcNA/8FmZYzhb1A="

jobs:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.7-dev
    - python: 3.8
    - python: 3.8-dev
    - python: 3.9-dev
  allow_failures:
    - python: 3.9-dev

before_install:
  - python -m pip install --upgrade pip setuptools wheel
  - pip install -r requirements_dev.txt
install:
  - check-manifest
  - python setup.py sdist bdist_wheel
  - twine check dist/*
script:
  - pytest
after_success:
  - curl -s https://codecov.io/bash | bash
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == false ]]; then
      twine upload --skip-existing dist/*
    fi

notifications:
  email:
    recipients:
      - ellert_vandervelden@outlook.com
    on_success: change
    on_failure: always
